---
title: "almond_SA_Ted"
author: "Yingfei Jiang"
date: "4/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(sensitivity)
library(pse)

clim <- read.table("clim.txt")
```
# LHS method, 1000 iterations
```{r}
#Evaluating all five parameters
factors = c("a", "b", "c", "d", "e")

#Run 1000 sets
nsets = 1000

#Choose distributions
q = rep("qnorm", 5)
q.arg = list(list(mean=-0.015, sd=0.015/5), list(mean=-0.0046, sd=0.0046/5), list(mean=-0.07, sd=0.07/5), list(mean=0.0043, sd=0.0043/5), list(mean=0.28, sd=0.28/5))

#Generate samples from LHS
sens_almond_lhs = LHS(NULL, factors, nsets, q, q.arg)
sens_pars_lhs = get.data(sens_almond_lhs)
#head(sens_pars_lhs)


#Calculate and store results
source("almond_anomaly.R")
tmp = mapply(FUN = almond_anomaly, a = sens_pars_lhs$a, b = sens_pars_lhs$b, c = sens_pars_lhs$c, d = sens_pars_lhs$d, e = sens_pars_lhs$e, MoreArgs = list(clim_data = clim, mean_only = TRUE))

sens_result_lhs = matrix(tmp)
colnames(sens_result_lhs) = c("mean_anomaly_1000")
```

```{r}
sens_almond_lhs = pse::tell(sens_almond_lhs, t(sens_result_lhs), res.names = c("mean_anomaly"))
# x-y parameter plot
pse::plotscatter(sens_almond_lhs, col="blue", cex=5)
# cummulative distribution
pse::plotecdf(sens_almond_lhs,  col="blue", cex=5)
# partial rank correlation
pse::plotprcc(sens_almond_lhs, ylab = "Correlation")
sens_almond_lhs$prcc
```

```{r}
sens_result_lhs = as.data.frame(sens_result_lhs) %>% 
  gather(value="value", key="yield")

ggplot(sens_result_lhs, aes(y = value, x = yield))+
  geom_boxplot()+
  labs(y="Mean Yield Anomoly")+
  theme_minimal()
```
# LHS method, 2000 iterations
```{r}
#Run 2000 sets
nsets_2 = 2000

#Generate samples from LHS
sens_almond_lhs_2 = LHS(NULL, factors, nsets_2, q, q.arg)
sens_pars_lhs_2 = get.data(sens_almond_lhs_2)


#Calculate and store results
tmp = mapply(FUN = almond_anomaly, a = sens_pars_lhs_2$a, b = sens_pars_lhs_2$b, c = sens_pars_lhs_2$c, d = sens_pars_lhs_2$d, e = sens_pars_lhs_2$e, MoreArgs = list(clim_data = clim, mean_only = TRUE))

sens_result_lhs_2 = matrix(tmp)
colnames(sens_result_lhs_2) = c("mean_anomaly_2000")
```

```{r}
sens_almond_lhs_2 = pse::tell(sens_almond_lhs_2, t(sens_result_lhs_2), res.names = c("mean_anomaly"))
pse::plotscatter(sens_almond_lhs_2, col="blue", cex=5)
pse::plotecdf(sens_almond_lhs_2,  col="blue", cex=5)

pse::plotprcc(sens_almond_lhs_2, ylab = "Correlation")
sens_almond_lhs_2$prcc
```

```{r}
sens_result_lhs_2 = as.data.frame(sens_result_lhs_2) %>% 
  gather(value="value", key="yield")

ggplot(sens_result_lhs_2, aes(y = value, x = yield))+
  geom_boxplot()+
  labs(y="Mean Yield Anomoly")+
  theme_minimal()
```

```{r}
lhs_compare = rbind(sens_result_lhs, sens_result_lhs_2)

ggplot(lhs_compare, aes(y = value, x = yield))+
  geom_boxplot()+
  labs(y="Mean Yield Anomoly")+
  theme_minimal()
```

# Sobel method, 1000 iterations.
```{r}
np = 1000
a = rnorm(mean=-0.015, sd=0.015/5, n = np)
b = rnorm(mean=-0.0046, sd=0.0046/5, n = np)
c = rnorm(mean=-0.07, sd=0.07/5, n = np)
d = rnorm(mean=0.0043, sd=0.0043/5, n = np)
e = rnorm(mean=0.28, sd=0.28/5, n = np)

X1 = cbind.data.frame(a, b, c, d, e)

a = rnorm(mean=-0.015, sd=0.015/5, n = np)
b = rnorm(mean=-0.0046, sd=0.0046/5, n = np)
c = rnorm(mean=-0.07, sd=0.07/5, n = np)
d = rnorm(mean=0.0043, sd=0.0043/5, n = np)
e = rnorm(mean=0.28, sd=0.28/5, n = np)

X2 = cbind.data.frame(a, b, c, d, e)

sens_almond_sobel = sobol2007(model = NULL, X1, X2, nboot = 100)

tmp = mapply(FUN = almond_anomaly, a = sens_almond_sobel$X$a, b = sens_almond_sobel$X$b, c = sens_almond_sobel$X$c, d = sens_almond_sobel$X$d, e = sens_almond_sobel$X$e, MoreArgs = list(clim_data = clim, mean_only = TRUE))

sens_result_sobel = matrix(tmp)
colnames(sens_result_sobel) = c("mean_anomaly_1000")
```

```{r}
sens_almond_sobel = sensitivity::tell(sens_almond_sobel, sens_result_sobel, res.names = "mean_anomaly")

# first-order indices (main effect without co-variance)
sens_almond_sobel$S

# total sensitivity index
sens_almond_sobel$T

print(sens_almond_sobel)
plot(sens_almond_sobel)
```

```{r}
sens_result_sobel = as.data.frame(sens_result_sobel) %>% 
  gather(value="value", key="yield")

ggplot(sens_result_sobel, aes(y = value, x = yield))+
  geom_boxplot()+
  labs(y="Mean Yield Anomoly")+
  theme_minimal()

ggplot(sens_result_sobel, aes(value)) +
  stat_ecdf(geom = "step") +
  xlab("Mean Yield Anomaly (ton/acre)")
```

# Sobel method, 2000 iterations.
```{r}
np_2 = 2000
a = rnorm(mean=-0.015, sd=0.015/5, n = np_2)
b = rnorm(mean=-0.0046, sd=0.0046/5, n = np_2)
c = rnorm(mean=-0.07, sd=0.07/5, n = np_2)
d = rnorm(mean=0.0043, sd=0.0043/5, n = np_2)
e = rnorm(mean=0.28, sd=0.28/5, n = np_2)

X1 = cbind.data.frame(a, b, c, d, e)

a = rnorm(mean=-0.015, sd=0.015/5, n = np_2)
b = rnorm(mean=-0.0046, sd=0.0046/5, n = np_2)
c = rnorm(mean=-0.07, sd=0.07/5, n = np_2)
d = rnorm(mean=0.0043, sd=0.0043/5, n = np_2)
e = rnorm(mean=0.28, sd=0.28/5, n = np_2)

X2 = cbind.data.frame(a, b, c, d, e)

sens_almond_sobel_2 = sobol2007(model = NULL, X1, X2, nboot = 200)

tmp = mapply(FUN = almond_anomaly, a = sens_almond_sobel_2$X$a, b = sens_almond_sobel_2$X$b, c = sens_almond_sobel_2$X$c, d = sens_almond_sobel_2$X$d, e = sens_almond_sobel_2$X$e, MoreArgs = list(clim_data = clim, mean_only = TRUE))

sens_result_sobel_2 = matrix(tmp)
colnames(sens_result_sobel_2) = c("mean_anomaly_2000")
```

```{r}
sens_almond_sobel_2 = sensitivity::tell(sens_almond_sobel_2, sens_result_sobel_2, res.names = "mean_anomaly")

# first-order indices (main effect without co-variance)
sens_almond_sobel_2$S

# total sensitivity index
sens_almond_sobel_2$T

print(sens_almond_sobel_2)
plot(sens_almond_sobel_2)
```

```{r}
sens_result_sobel_2 = as.data.frame(sens_result_sobel_2) %>% 
  gather(value="value", key="yield")

ggplot(sens_result_sobel_2, aes(y = value, x = yield))+
  geom_boxplot()+
  labs(y="Mean Yield Anomoly")+
  theme_minimal()

ggplot(sens_result_sobel_2, aes(value)) +
  stat_ecdf(geom = "step") +
  xlab("Mean Yield Anomaly (ton/acre)")
```

```{r}
sobel_compare = rbind(sens_result_sobel, sens_result_sobel_2)

ggplot(sobel_compare, aes(y = value, x = yield))+
  geom_boxplot()+
  labs(y="Mean Yield Anomoly")+
  theme_minimal()
```